name: remote-sensing
channels:
    - defaults
    - conda-forge
dependencies:
    - python==3.10.*
    - pip
    - numpy
    - scipy
    - pandas
    - matplotlib
    - scikit-image
    - xlandsat
    - jupyter
    - jupyterlab
    - livereload
