name: remote-sensing
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.*
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - matplotlib-scalebar
  - scikit-image
  - xlandsat
  - pooch
  - tqdm
  - jupyter
  - jupyterlab
  - livereload
