name: remote-sensing
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - numpy
    - scipy
    - pandas
    - matplotlib
    - scikit-image
    - jupyter
    - jupyterlab
